### ISSUE TITLE
Getting setup

### ISSUE THREAD

**Issue by Bradster56** [hpe-linux/liberty#4]
When you guys first came to liberty, you gave us a list of commands and instructions on how to setup our virtual images so that we could program and be connected to github. Can you give me those commands so I can get them set up on my devices at home and at school? 

Thank you,
Brady

**Comment by powersj** [comment]
Hey Brady,

I'm trying to remember what exactly we talked about, but I think it was about getting started with git, downloading the C repo we used, and then getting the compiler working. 

To start with git, you will want to 'clone' the repo we were using. To do that, run the following command:

`git clone https://github.com/hpe-linux/liberty_c_git.git`

That will create a directory called liberty_c_git where you can then navigate to and work on that code there.

Next, to actually build the c code you will want to use apt to install things, like this:

`apt update`
`apt install build-essential`

Then you can run the makefile to build your code, make the file executable, and run it by doing the following:

make`
`chmod +x hello`
`./hello`

Hope that helps! Let me know if you had other questions.
