### ISSUE TITLE
Git hub Problems

### ISSUE THREAD

**Issue by yashprince123456** [hpe-linux/liberty#5]
Hello, 
So I was having trouble with viewing my code once I uploaded it to GitHub. I try to view it to as a Raw file, but that does not show any code. Could you please help me with this?
Thanks, 
Yash

**Comment by powersj** [comment]
Hi Yash!

Looks like you uploaded the binary that gets produced by running make and not the actual source code. The binary produced is not a human readable file and that is why you are getting that error.

Go back and upload the fib.c file you wrote and the makefile and then you will be able to view the code.

Developers typically do not upload binaries or keep them in version control. Instead a developer keeps his or her source code in version control and when it comes to build, builds the binary and then uses it as necessary.
